apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: custom-jenkins-build
spec:
  source:                       
    git:
      uri: https://github.com/hawkpatrick/custom-jenkins-openshift
      ref: "master"
    type: Git
  strategy:                     
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'jenkins:latest'
        namespace: openshift
      env:
        - name: CASC_JENKINS_CONFIG
          value: $JENKINS_HOME/casc_configs
    type: Source
  output:                       
    to:
      kind: ImageStreamTag
      name: custom-jenkins:latest
      namepsace: patrick-hock-code


